import math
import os
import re
from functools import lru_cache
from pathlib import Path
from typing import Any


BASE_DIR = Path(__file__).resolve().parents[1]
DOCUMENTS_DIR = BASE_DIR / "documents"
RAW_PAPERS_DIR = BASE_DIR / "papers" / "raw_pdfs"
DEFAULT_FAISS_DIR = BASE_DIR / "papers" / "embeddings" / "faiss_index"
EMBEDDING_MODEL = "text-embedding-3-small"
TOKEN_PATTERN = re.compile(r"[A-Za-z0-9가-힣]+")


def _faiss_dir() -> Path:
    override = os.getenv("CHAT_GRAPH_FAISS_DIR")
    return Path(override).expanduser().resolve() if override else DEFAULT_FAISS_DIR


def _tokenize(text: str) -> set[str]:
    return {
        token.lower()
        for token in TOKEN_PATTERN.findall(text)
        if len(token.strip()) > 1
    }


def _chunk_text(text: str, chunk_size: int = 900, overlap: int = 120) -> list[str]:
    normalized = re.sub(r"\s+", " ", text).strip()
    if not normalized:
        return []

    chunks = []
    start = 0
    while start < len(normalized):
        end = min(start + chunk_size, len(normalized))
        chunks.append(normalized[start:end])
        if end >= len(normalized):
            break
        start = max(end - overlap, start + 1)
    return chunks


@lru_cache(maxsize=1)
def _load_document_chunks() -> list[dict[str, Any]]:
    chunks: list[dict[str, Any]] = []
    paths = sorted(DOCUMENTS_DIR.glob("tb_*.txt"))
    if not paths:
        print(f"[retriever] keyword fallback found no tb_*.txt docs under {DOCUMENTS_DIR}")
        paths = sorted(DOCUMENTS_DIR.glob("*.txt"))
    if not paths:
        print(f"[retriever] keyword fallback found no text docs under {DOCUMENTS_DIR}")
        paths = sorted(RAW_PAPERS_DIR.glob("*.txt"))
    if not paths:
        print(
            "[retriever] keyword fallback found no text docs under "
            f"{DOCUMENTS_DIR} or {RAW_PAPERS_DIR}"
        )
        return chunks

    print(f"[retriever] keyword fallback found {len(paths)} text docs")
    for path in paths:
        try:
            text = path.read_text(encoding="utf-8")
        except OSError:
            print(f"[retriever] keyword fallback skipped unreadable doc: {path}")
            continue

        for index, content in enumerate(_chunk_text(text)):
            chunks.append(
                {
                    "source": str(path.relative_to(BASE_DIR)),
                    "content": content,
                    "chunk_index": index,
                    "tokens": _tokenize(content),
                }
            )
    return chunks


@lru_cache(maxsize=1)
def _load_faiss_store():
    try:
        from langchain_community.vectorstores import FAISS
        from langchain_openai import OpenAIEmbeddings

        faiss_dir = _faiss_dir()
        if not faiss_dir.exists():
            print(f"[retriever] FAISS index not found at {faiss_dir}")
            return None

        embeddings = OpenAIEmbeddings(model=EMBEDDING_MODEL)
        # This enables loading LangChain's pickle sidecar only for the FAISS index
        # generated by this project from local documents/tb_*.txt files.
        store = FAISS.load_local(
            str(faiss_dir),
            embeddings,
            allow_dangerous_deserialization=True,
        )
        print(f"[retriever] loaded FAISS index from {faiss_dir}")
        return store
    except Exception as exc:
        print(f"[retriever] FAISS load failed, using keyword fallback: {type(exc).__name__}: {exc}")
        return None


def _normalize_faiss_score(raw_score: float) -> float:
    try:
        distance = max(float(raw_score), 0.0)
    except (TypeError, ValueError):
        return 0.0
    return 1.0 / (1.0 + distance)


def _retrieve_with_faiss(query: str, top_k: int) -> list[dict[str, Any]]:
    store = _load_faiss_store()
    if store is None:
        return []

    try:
        matches = store.similarity_search_with_score(query, k=top_k)
        print("[retriever] using FAISS retriever")
    except Exception as exc:
        print(f"[retriever] FAISS search failed, using keyword fallback: {type(exc).__name__}: {exc}")
        return []

    results = []
    for doc, raw_score in matches:
        metadata = getattr(doc, "metadata", {}) or {}
        content = getattr(doc, "page_content", "") or ""
        if not content.strip():
            continue
        results.append(
            {
                "source": str(metadata.get("source", "tb_faiss_index")),
                "content": content[:1200],
                "score": round(_normalize_faiss_score(raw_score), 4),
                "retriever": "faiss",
            }
        )
    return results


def _retrieve_with_keywords(query: str, top_k: int) -> list[dict[str, Any]]:
    query_tokens = _tokenize(query)
    if not query_tokens:
        print("[retriever] keyword fallback skipped: empty query tokens")
        return []

    scored = []
    for chunk in _load_document_chunks():
        chunk_tokens = chunk["tokens"]
        overlap = query_tokens & chunk_tokens
        if not overlap:
            continue
        denominator = math.sqrt(len(query_tokens)) * math.sqrt(len(chunk_tokens))
        score = len(overlap) / denominator if denominator else 0.0
        scored.append((score, chunk))

    scored.sort(key=lambda item: item[0], reverse=True)
    results = [
        {
            "source": chunk["source"],
            "content": chunk["content"],
            "score": round(float(score), 4),
            "retriever": "keyword",
        }
        for score, chunk in scored[:top_k]
    ]
    print(f"[retriever] retrieved {len(results)} docs using keyword fallback")
    return results


def retrieve_documents(query: str, top_k: int = 3) -> list[dict[str, Any]]:
    faiss_results = _retrieve_with_faiss(query, top_k)
    if faiss_results:
        return faiss_results
    print("[retriever] using keyword fallback retriever")
    return _retrieve_with_keywords(query, top_k)


def evaluate_retrieval_quality(
    results: list[dict[str, Any]],
    threshold: float = 0.2,
) -> tuple[str, str]:
    if not results:
        return "insufficient", "no documents retrieved"

    best_score = max(float(item.get("score", 0.0) or 0.0) for item in results)
    if best_score < threshold:
        print(f"[retrieval_quality] quality=low, top_score={best_score:.4f}")
        return "low", f"best score {best_score:.2f} below threshold {threshold:.2f}"
    if best_score < threshold + 0.15:
        print(f"[retrieval_quality] quality=medium, top_score={best_score:.4f}")
        return "medium", f"best score {best_score:.2f} is usable but limited"
    print(f"[retrieval_quality] quality=high, top_score={best_score:.4f}")
    return "high", f"best score {best_score:.2f} is sufficient"
